### ISSUE TITLE
Cross-platform release binaries

### ISSUE THREAD

**Issue by sujitawake** [dhth/mult#2]
Looks like a good project. Thanks for writing one!

Would it be possible to provide compiled binaries across different OS flavours e.g. OSX (Intel, and Apple Silicon), Linux, Windows etc? This would avoid the hassle of manual compilations.

**Comment by dhth** [comment]
Thanks!

I've [released](https://github.com/dhth/mult/releases) this via Github releases now. There are binaries for linux, darwin, and windows for the architectures `386`, `amd64`, and `arm64`. Let me know if you you're on a platform other than these.
